ICEBREAKERS = [
    "Do you have any hidden talents?",
    "Do you prefer the beach or the mountains?",
    "If you could go anywhere in the world, where would you go and why?",
    "What's your favorite hobby?",
    "What's your favorite book/movie/TV show?",
    "What do you like to do outside of work?",
    "If you could be a character in any TV show or movie, who would you be and why?",
    "If you could have any fictional character as a best friend, who would it be and why?",
    "What's your favorite type of cuisine?",
    "What's your go-to snack or guilty pleasure food?",
    "If you could only eat one dish for the rest of your life, what would it be?",
    "What's the weirdest food combination you've ever tried, and did you like it?",
    "What's the most useful tech tip or trick you've learned?",
    "What's your favorite tech gadget or tool, and why?",
    "What's the latest tech trend that's caught your attention?",
    "What's the most beautiful natural wonder you've ever seen while traveling?",
    "If you could have any superpower, what would it be and why?",
    "What's the best advice you've ever received?",
    "Do you have a favorite hobby, and how did you get into it?",
    "Are you an early bird or night owl?",
    "Tea or coffee?",
    "Are you a cat person or a dog person?",
    "What was the silliest thing you or someone else has ever said during a meeting?",
    "What do you like most about remote work?",
    "What is your useless superpower?",
    "Where is your dream location to work from?",
    "How do you stay motivated working virtually?",
    "Altogether, what is your favorite thing about your team?",
    "If you could be anyone in this world, other than yourself, who would you be?",
    "Tell us 5 things you always carry in a bag?",
    "What is the last song you heard?",
    "Are you a planner or a spontaneous person?",
    "How do you relieve stress and anxiety?",
    "What is the scariest thing you've ever done for fun?",
    "What is a team-building activity that you secretly hate?",
    "What historical figure would you meet?",
    "What's one thing that always makes you laugh no matter what kind of mood you're in?",
    "What makes you feel happy about life right now?",
    "Who is the most inspirational person that you've ever met?",
    "Do you care about your zodiac sign?",
    "Pick your favorite decade and explain why!",
    "What excuse do you use all the time?",
    "What are the five things that are the most important to you except friends and family?",
    "If you weren't at work right now, what would you be doing?",
    "Would you instead choose "wisdom" or "money"?",
    "Which skill have you learned during working from home?",
    "What superpower do you wish you could wake up and have tomorrow?",
    "Are you a listener or a talker?",
    "What type of person do you love working with the most?",
    "What quality do you appreciate most in a friend?",
    "What are your favorite team building activities?",
    "What superpower would you give to your coworkers?",
    "How would you describe your laugh?",
    "You're only good as your team: True or false?",
    "What is your earliest memory of teamwork?",
    "What was your first job?",
    "If you could choose your own personality, would you like to be an introvert or extrovert?",
    "The best thing that ever happened to you so far?",
    "What are languages you can speak?",
    "Work from home or office culture?",
    "What are the interesting skills you want to learn?",
    "What lockdown lifestyle teaches you?",
    "Do first impressions matter?",
    "What are your favorite hobbies?",
    "What is one thing you will never do again?",
    "What makes you laugh more than anything?",
    "Beach or mountain?",
    "In your opinion, what is the most beautiful place on earth?",
    "What's your favorite way to travel?",
    "If you could visit any place in the world, where would it be?",
    "Where are the best places to travel alone?",
    "What's the longest trip you've ever taken?",
    "Road-trip or airplane?",
    "If I visit your country, what's the one meal I shouldn't miss?",
    "What's the best city in the world?",
    "What fictional world or place would you like to visit?",
    "Which country do you wish to travel to?",
    "What is your favorite genre of music?",
    "Name TV shows that you would recommend to everyone?",
    "What's your favorite cartoon character and why?",
    "What skill do you think everyone should have?",
    "If you could kill any fashion trend forever what would it be?",
    "Which song can you listen to all day long?",
    "If you could have dinner with a fictional character, who would you choose?",
    "What is your favorite sport to watch?",
    "Money can't buy happiness: True or false?",
    "What is the most useless talent you have?",
    "What book did you read that changed your life the most?",
    "What are the most ridiculous things you've bought?",
    "What is the oldest thing you own?",
    "What outdated slang do you still use?",
    "Childhood life or adulthood life?",
    "What is your best school/college memory?",
    "What is your favorite style of clothing?",
    "Which game do you play the most?",
    "How do you like your eggs?",
    "If you can only eat one food for the rest of your life, what is it?",
    "What's your least favorite food?",
    "Coffee or tea?",
    "Beer or cocktail?",
    "What's the weirdest food you've ever eaten?",
    "Can you live without desserts?",
    "Share an unusual food pairing that you enjoy!",
    "What is the grossest food you ever had?",
    "Pizza or sushi?",
    "Carbonara or Bolognese?",
    "What is your guilty pleasure food?",
    "What's your favorite café?",
    "Do you think computers will ever take over the world?",
    "Is technology something to appreciate or fear?",
    "If you could only use one piece of technology, what would it be?",
    "What are your top three most used emoji in text?",
    "Can you live without your smartphone for 24 hours?",
    "What is your favorite technology brand?",
    "What is your favorite way to waste time online?",
    "If you have a time machine. When and where would you like to visit first?",
    "If you have to delete all the apps but can keep a maximum of three, what apps would you keep?",
    "What's your favorite emoji?",
    "Would you delete your social media for your mental peace?",
    "If you could go back in time with the knowledge you currently have, what age would you choose, and why?",
    "If you had all the time, money, and resources, would you still work?",
    "Do you prefer to be able to speak to animals or speak all languages?",
    "If you ever met an alien, what would you ask?",
    "Would you rather lose your sight or hearing?",
    "Who would you want on your team in a zombie apocalypse?",
    "Would you rather live in the ocean or the jungle?",
    "If you could be immortal, what age would you choose to stop aging at?",
    "What is the most challenging aspect of your job right now?",
    "Who influenced you the most when you were growing up?",
    "What's the best piece of advice you've ever received?",
    "What would you do if you had all the money in the world?",
    "If you could give a piece of advice to your younger self, what would it be?",
    "If you could go back to your childhood, what would you learn and master over the years so you'd be an expert at it today?",
    "What one thing would you change about our society?",
    "If you have the authority to change the law, what law would you change?",
    "If money was not an issue, what would you be doing with your life?",
    "When you die, what do you want to be remembered for?",
    "What is your moment of achievement?",
    "Have you found the purpose of your life?",
    "What motivates you in life?",
    "What title would you give this chapter in your life?",
]