"""added field for excluding users

Revision ID: 00dd6903b9ac
Revises: 0f7bb2b3b46a
Create Date: 2022-11-22 12:50:01.384421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00dd6903b9ac"
down_revision = "0f7bb2b3b46a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_members",
        sa.Column("is_opted", sa.Boolean(), server_default="t", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_members", "is_opted")
    # ### end Alembic commands ###
