"""include enterprise id

Revision ID: 0a5b93abe5ad
Revises: 9baf92e85c82
Create Date: 2022-08-07 21:07:51.559728

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0a5b93abe5ad"
down_revision = "9baf92e85c82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("enterprise_id", sa.String(), nullable=True))
    op.alter_column("channels", "created_on", new_column_name="added_on")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("channels", "added_on", new_column_name="created_on")
    op.drop_column("channels", "enterprise_id")
    # ### end Alembic commands ###
