"""include conversation tracking

Revision ID: 0f7bb2b3b46a
Revises: d58c4e427ba6
Create Date: 2022-08-15 21:41:38.978637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0f7bb2b3b46a"
down_revision = "d58c4e427ba6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("team_id", sa.String(), nullable=True),
        sa.Column(
            "conversations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_on", sa.Date(), nullable=True),
        sa.Column("sent_on", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id", "team_id"],
            ["channels.channel_id", "channels.team_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_conversations_channel_id"),
        "channel_conversations",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_channel_conversations_id"),
        "channel_conversations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_channel_conversations_team_id"),
        "channel_conversations",
        ["team_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_channel_conversations_team_id"), table_name="channel_conversations"
    )
    op.drop_index(
        op.f("ix_channel_conversations_id"), table_name="channel_conversations"
    )
    op.drop_index(
        op.f("ix_channel_conversations_channel_id"), table_name="channel_conversations"
    )
    op.drop_table("channel_conversations")
    # ### end Alembic commands ###
