"""added field to track match_number

Revision ID: 1771f08e8a2a
Revises: 00dd6903b9ac
Create Date: 2022-12-30 17:14:11.680762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1771f08e8a2a'
down_revision = '00dd6903b9ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('next_match_number', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'next_match_number')
    # ### end Alembic commands ###
