"""remove foreign id

Revision ID: 42df61cb6bc6
Revises: 0a5b93abe5ad
Create Date: 2022-08-14 16:03:28.720805

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "42df61cb6bc6"
down_revision = "0a5b93abe5ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "channel_members_channel_id_fkey", "channel_members", type_="foreignkey"
    )
    op.drop_index("ix_channels_channel_id", table_name="channels")
    op.create_index(
        op.f("ix_channels_channel_id"), "channels", ["channel_id"], unique=False
    )
    op.create_unique_constraint("channel_uc", "channels", ["channel_id", "team_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("channel_uc", "channels", type_="unique")
    op.drop_index(op.f("ix_channels_channel_id"), table_name="channels")
    op.create_index("ix_channels_channel_id", "channels", ["channel_id"], unique=False)
    op.create_foreign_key(
        "channel_members_channel_id_fkey",
        "channel_members",
        "channels",
        ["channel_id"],
        ["channel_id"],
    )
    # ### end Alembic commands ###
