"""added column to keep track of current structure of round robin circle

Revision ID: 60e35f44f3bf
Revises: 00dd6903b9ac
Create Date: 2022-12-31 13:24:22.063900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60e35f44f3bf'
down_revision = '00dd6903b9ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('members_circle', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'members_circle')
    # ### end Alembic commands ###
