"""members_cache

Revision ID: 9baf92e85c82
Revises: 19a557b61f6d
Create Date: 2022-07-24 21:45:59.265379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9baf92e85c82"
down_revision = "19a557b61f6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("member_id", sa.String(), nullable=True),
        sa.Column("added_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "member_id", name="channel_member_uc"),
    )
    op.create_index(
        op.f("ix_channel_members_channel_id"),
        "channel_members",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_channel_members_id"), "channel_members", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_members_id"), table_name="channel_members")
    op.drop_index(op.f("ix_channel_members_channel_id"), table_name="channel_members")
    op.drop_table("channel_members")
    # ### end Alembic commands ###
