"""Add configurable frequency of pairings

Revision ID: c680f8e009de
Revises: 60e35f44f3bf
Create Date: 2024-07-31 17:39:58.304294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c680f8e009de'
down_revision = '60e35f44f3bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('conversation_frequency_weeks', sa.Integer(), server_default='2', nullable=False))
    op.add_column('channels', sa.Column('send_midpoint_reminder', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'send_midpoint_reminder')
    op.drop_column('channels', 'conversation_frequency_weeks')
    # ### end Alembic commands ###
