"""add team id for uniqueness

Revision ID: d58c4e427ba6
Revises: 42df61cb6bc6
Create Date: 2022-08-14 16:05:29.910955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d58c4e427ba6"
down_revision = "42df61cb6bc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channel_members", sa.Column("team_id", sa.String(), nullable=True))
    op.drop_constraint("channel_member_uc", "channel_members", type_="unique")
    op.create_unique_constraint(
        "channel_member_uc", "channel_members", ["channel_id", "member_id", "team_id"]
    )
    op.create_index(
        op.f("ix_channel_members_team_id"), "channel_members", ["team_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "channel_members",
        "channels",
        ["channel_id", "team_id"],
        ["channel_id", "team_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "channel_members", type_="foreignkey")
    op.drop_index(op.f("ix_channel_members_team_id"), table_name="channel_members")
    op.drop_constraint("channel_member_uc", "channel_members", type_="unique")
    op.create_unique_constraint(
        "channel_member_uc", "channel_members", ["channel_id", "member_id"]
    )
    op.drop_column("channel_members", "team_id")
    # ### end Alembic commands ###
